### ISSUE TITLE
Catch Error When Snum Names Have Been Changed

### ISSUE THREAD

**Issue by ehmurray8** [ehmurray8/KytonUI#24]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\phils\Documents\FbgUI\program.py", line 278, in connect_devices
    self.program_loop()
  File "C:\Users\phils\Documents\FbgUI\cal_program.py", line 18, in program_loop
    self.cal_loop(temps_arr)
  File "C:\Users\phils\Documents\FbgUI\cal_program.py", line 39, in cal_loop
    start_temp, waves, amps, CAL, self.table, 0.0, False)
  File "C:\Users\phils\Documents\FbgUI\file_helper.py", line 61, in write_db
    cur.execute(sql)
sqlite3.OperationalError: table cal33 has no column named KY1001PKOPEN Wavelength (nm.)

**Comment by ehmurray8** [comment]
Catching this error in the code, having this stop the connection thread. Need to have this be logged in the log view.

**Comment by ehmurray8** [comment]
Logged in logview
