### ISSUE TITLE
Need to properly kill threads on closing

### ISSUE THREAD

**Issue by ehmurray8** [ehmurray8/KytonUI#9]

**Comment by ehmurray8** [comment]
Async event loop, and helper threads remain open after closing.

**Comment by ehmurray8** [comment]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\phils\Documents\FbgUI\program.py", line 269, in connect_devices
    self.master.conn_buttons[LASER]()
  File "C:/Users/phils/Documents/FbgUI/main_program.py", line 180, in <lambda>
    self.conn_buttons[dev_text] = lambda: self.conn_dev(loc_ent, port_ent, dev_text)
  File "C:/Users/phils/Documents/FbgUI/main_program.py", line 221, in conn_dev
    self.laser = devices.SM125(loc_ent.get(), int(port_ent.get()), self.loop, self.use_dev)
  File "C:\Users\phils\Documents\FbgUI\devices.py", line 24, in __init__
    self.loop.run_until_complete(self.connect_dev(address, port))
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\phils\AppData\Local\Programs\Python362\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

**Comment by ehmurray8** [comment]
Seems to be fixed by removing long async sleeps in edf3836. As stated in #10 may need to remove async code or at least clean it up.

**Comment by ehmurray8** [comment]
Race condition could rarely occur if trying to restart program quickly while program is sleeping for switch change.

**Comment by ehmurray8** [comment]
Race condition may occur, hopefully fixing #6 fixes this, otherwise this error isn't fatal and should very rarely occur if at all.
